### ISSUE TITLE
`set-output` command is deprecated 

### ISSUE THREAD

**Issue by pakhilov** [bahmutov/gh-build-matrix#1]
I am experiencing an issue with the following error message:

"Warning: The set-output command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/"

I believe the problem is related to the gh-build-matrix project, specifically the entrypoint.sh file. In particular, the following lines seem to be causing the issue:

`echo "::set-output name=matrix::$OUTPUT"

echo ${OUTPUT}`

Can you please resolve this issue?

Thank you!
![Screenshot 2022-12-29 at 10 51 14 AM](https://user-images.githubusercontent.com/10390058/209996422-2dfb2488-749a-4b23-86e8-67413806f16d.png)

**Comment by bahmutov** [comment]
How do they suggest we fix the output in this `.sh` file? In JS I could use `actions/core` NPM module, but what do they suggest to do in shell files?

**Comment by pakhilov** [comment]
All examples on how to use the recommended changes show code in either yaml or in PowerShell.


echo "outputview=matrix" >> GITHUB_OUTPUT
echo ${outputview}
